### ISSUE TITLE
Add peer router id into get_bgp_neighbors_detail()

### ISSUE THREAD

**Issue by inetuid** [napalm-automation/napalm-base#40] opened 2016-06-17 16:01 UTC
At present the remote peer router id is only available in the output of get_bgp_neighbors() and not in get_bgp_neighbors_detail().

@dbarrosop suggested that get_bgp_neighbors_detail()[my_vrf][my_neigh_ip] could be used to get this information (slight typo I think, probably should be get_bgp_neighbors()[my_vrf][my_neigh_ip]) but that supposes that you have the VRF information available (or else you have to loop through the VRFs to find the peer).

If 'routing_table' in get_bgp_neighbors_detail() is the same as the VRF in get_bgp_neighbors() then this isn't an issue. If they are not, then I propose adding the remote peer router id into the get_bgp_neighbors_detail() method.

**Comment by mirceaulinic** [comment] 2016-06-17 23:07
I can add the peer router id information for all devices supporting ```get_bgp_neighbors_detail``, no problem.

**Comment by dbarrosop** [comment] 2016-06-18 11:40
> but that supposes that you have the VRF information available (or else you have to loop through the VRFs to find the peer).

How else are you supposed to do it? You need to know what you are looking for or loop through the data. I actually realized that `get_bgp_neighbors_detail` and `get_bgp_config` are flawed by design as I just realized they don't support VRF. We will have to revisit that.

**Comment by inetuid** [comment] 2016-06-23 19:11
Not sure if the docs reflect reality, but for get_bgp_neighbors() the docs say 

> The keys for the first dictionary will be the vrf

so that suggests its VRF aware.
.

**Comment by mirceaulinic** [comment] 2016-06-27 11:18
Indeed ```get_bgp_neighbors``` does, but ```get_bgp_neighbors_detail``` does not, although it should. But this will be probably fixed soon and both will have VRF support!

**Comment by mirceaulinic** [comment] 2016-06-27 11:18
Thanks @inetuid for raising this issue!

**Comment by dbarrosop** [comment] 2016-09-10 11:09
Can we close this one?

**Comment by mirceaulinic** [comment] 2016-09-18 12:35
Yes, the latest release contains these details now. We can close this issue.

**Closed** 2016-09-18 13:12 UTC
Labels: internal
